adding bloodborne fan campaign
argonui/SCED pull request #262
Opened 2023-04-13 14:32 UTC by Chr1Z93

This adds the fan campaign "Bloodborne - City of the Unseen" by aughhhh

2023-04-17 03:22 UTC, BootleggerFinn requested changes

2023-04-17 03:22 UTC, BootleggerFinn commented on objects/Fan-MadeScenariosCampaignsMiscellany.66e97c/Fan-MadeCampaigns.89c32e.json
Would it be alright if we kept these in the alphabetical order they are mostly in?  Moving just The ColorOutofOz and BloodborneCityoftheUnseen

2023-04-17 03:22 UTC, BootleggerFinn commented on objects/Fan-MadeScenariosCampaignsMiscellany.66e97c/Fan-MadeStandaloneScenarios.5db60c.json
Likewise with this, if we could move this into the appropriate alphabetical order (Note that "The"s are ignored when beginning a title)

2023-04-17 07:19 UTC, Chr1Z93 commented on objects/Fan-MadeScenariosCampaignsMiscellany.66e97c/Fan-MadeCampaigns.89c32e.json
Updated

2023-04-17 07:19 UTC, Chr1Z93 commented on objects/Fan-MadeScenariosCampaignsMiscellany.66e97c/Fan-MadeStandaloneScenarios.5db60c.json
Updated

2023-04-18 21:51 UTC, BootleggerFinn approved these changes

2023-04-18 21:51 UTC, merged