added removal of Mythos data onCollisionExit
argonui/SCED pull request #268
Opened 2023-04-17 20:53 UTC by Chr1Z93

Side-Effect: Retrigger of title splash when changing difficulty (flipping scenario reference card)

2023-04-18 07:22 UTC, Buhallin commented
I don't think doubling up the splash is an acceptable side effect here.  Should leave the scenario name intact across removal (since the current logic only cares about a new one entering) but clear the data.

2023-04-18 07:22 UTC, Buhallin requested changes

2023-04-18 07:34 UTC, Chr1Z93 commented on src/core/MythosArea.ttslua
> +    currentScenario = nil
Good point, updated it.

2023-04-19 09:02 UTC, Buhallin approved these changes

2023-04-19 09:02 UTC, merged