Added Parallel Jim Investigator
argonui/SCED pull request #411
Opened 2023-10-14 02:17 UTC by Entrox-Licher

Added Parallel Jim Investigator (not his challenge scenario yet) and some minor fixes to old cards.

2023-10-14 08:09 UTC, Chr1Z93 commented
You need to update the id ranges here too:
https://github.com/argonui/SCED/blob/main/src/arkhamdb/ArkhamDb.ttslua#L200C6-L216C10

2023-10-14 14:20 UTC, Entrox-Licher commented
Done!  We should probably refactor that later to be some constant somewhere so it's easier to catch

2023-10-14 21:55 UTC, Chr1Z93 reviewed
Some nitpicking

2023-10-14 21:55 UTC, Chr1Z93 commented on objects/AllPlayerCards.15bb07/JimsTrumpet.03c6a7.json
> +  "Description": "The Dead Speak",
This should be "The Dead Listen"

2023-10-14 21:55 UTC, Chr1Z93 commented on objects/AllPlayerCards.15bb07/JimsTrumpet.7dfd5f.json
> +  "Description": "The Dead Speak (Advanced)",
This should be "The Dead Speak"

2023-10-14 21:55 UTC, Chr1Z93 commented on src/arkhamdb/DeckImporterMain.ttslua
> +        table.insert(spritList, i)
let's name this "spiritList" instead of "spritList" 😉

2023-10-16 06:43 UTC, Chr1Z93 requested changes

2023-10-16 06:43 UTC, Chr1Z93 commented on objects/AllPlayerCards.15bb07/JimsTrumpet.7dfd5f.json
> +  "Description": "The Dead Listen (Advanced)",
The advanced trumpet does actually say "The Dead Speak" 😅

2023-10-16 14:24 UTC, Chr1Z93 approved these changes

2023-10-16 14:25 UTC, merged