Unified custom content spawning
argonui/SCED pull request #456
Opened 2023-11-04 12:54 UTC by Chr1Z93

Custom content (that doesn't have a replacement box on the table) will now spawn directly below the tentacle stand in the first empty position (from left to right, max. 3 rows).

![image](https://github.com/argonui/SCED/assets/97286811/1747c11a-6117-4867-94ec-2b0e91ca6727)

2023-11-04 17:21 UTC, Entrox-Licher requested changes
There should probably be a consistent behaviour defined for what happens when all 3 rows are filled (like a broadcast that there is no room?), rather than just defaulting back to the random spawn positions of each given box

2023-11-04 18:03 UTC, Chr1Z93 commented
> There should probably be a consistent behaviour defined for what happens when all 3 rows are filled (like a broadcast that there is no room?), rather than just defaulting back to the random spawn positions of each given box

Fair point! Very unlikely, but I'll add a broadcast

2023-11-06 14:51 UTC, Entrox-Licher commented
I think it would be better to just block spawning altogether if full.  It's unlikely enough to happen that the inconvenience isn't huge, and it provides a consistent behaviour, rather than the boxes spawning all over the table and potentially falling into other bags, leading to more confusion.

2023-11-07 04:00 UTC, Entrox-Licher approved these changes

2023-11-07 04:00 UTC, merged