Added more FHV cards
argonui/SCED pull request #467
Opened 2023-11-11 09:50 UTC by Chr1Z93

- speak to the dead
- blackmail file

2023-11-11 15:10 UTC, Entrox-Licher requested changes

2023-11-11 15:10 UTC, Entrox-Licher commented on objects/AllPlayerCards.15bb07/SpeaktotheDead.c763aa.gmnotes
> +}
Missing `uses` metadata

2023-11-11 15:27 UTC, Chr1Z93 commented on objects/AllPlayerCards.15bb07/SpeaktotheDead.c763aa.gmnotes
> +}
Good catch!

2023-11-11 16:09 UTC, Chr1Z93 commented on objects/AllPlayerCards.15bb07/SpeaktotheDead.c763aa.gmnotes
> +}
fixed

2023-11-13 15:48 UTC, Entrox-Licher approved these changes

2023-11-13 15:48 UTC, merged