Added more preview cards
argonui/SCED pull request #498
Opened 2023-12-07 21:00 UTC by Chr1Z93

- added Ancestral Token
- added Fine Tuning
- added Key of Solomon
- added Purified
- added Drain Essence
- added Fake Credentials
- added Prismatic Spectacles
- added Kate + signatures
- added Transmogrify
- added Well-Dressed

2023-12-11 23:58 UTC, Entrox-Licher commented
Do you wanna go ahead and add slot metadata for these now that we have that?

2023-12-12 00:15 UTC, Chr1Z93 commented
> Do you wanna go ahead and add slot metadata for these now that we have that?

Done

2023-12-12 15:52 UTC, Entrox-Licher commented
Nitpick: Have the slot field after `type` instead of after `trait` for consistency

2023-12-12 19:04 UTC, Entrox-Licher requested changes
Minor change for Kate, other than that it looks good to go!

2023-12-12 19:07 UTC, Chr1Z93 commented on objects/AllPlayerCards.15bb07/KateWinthrop.ce2322.gmnotes
> +    "bonded": [
Good catch. Corrected it!

2023-12-12 19:11 UTC, Entrox-Licher approved these changes

2023-12-12 19:11 UTC, merged